### ISSUE TITLE
Included jar file does not contain application classes, just freemarker

### ISSUE THREAD

**Issue by ericlentz** [craigstjean/WebSphere-Deployment-Xml-Tool#1]
I think you forgot to run the build step before running the uberjar task. I recommend this change to your build.grade:

``` Gradle
task uberjar(dependsOn: build, type: Jar) {
```

After doing the build and the uberjar task the resulting jar file ran great and did what it was advertised to do. Nice tool.

**Comment by craigstjean** [comment]
Good call, updated with commit 6f4f7f3
